### ISSUE TITLE
404 NOT FOUND

### ISSUE THREAD

**Issue by Thaison03** [ISCASCIP/Semantic-Parsing#3]
Hi, I am looking for the code for Semantic Parsing of Pre-university Math Problems in your main page. But the link "https://github.com/casnlu/Semantic-Parsing/blob/" gets not found. May I ask if I can get this source code in anywhere?

**Comment by dongpobeyond** [comment]
@Thaison03  I also didn't find the code for this paper. I made a mistake and added an empty link. Now it has been updated. Thank you.
